[package]
name = "speedtestr"
version = "0.1.0"
authors = ["Zach Peters <zpeters@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
reqwest = "0.9.20"
serde_derive = "1.0.99"
serde = "1.0.100" 
serde_json = "1.0.40"
failure = "0.1.5" 
rand = "0.7.0"
