[package]
name = "speedtestr"
version = "0.1.0"
authors = ["Zach Peters <zpeters@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
reqwest = "0.10.1"
serde_derive = "1.0.101"
serde = "1.0.104" 
serde_json = "1.0.46"
failure = "0.1.6" 
rand = "0.7.3"
